table 'ดัชนีราคา ประเทศและภาค'
	lineageTag: b8c846c0-a0e7-409c-b970-672b065c5879

	measure 'เงินเฟ้อทั่วไป (%)' = VAR d = CALCULATE(MAX('ดัชนีราคา ประเทศและภาค'[เดือน]), REMOVEFILTERS()) RETURN CALCULATE(AVERAGE('ดัชนีราคา ประเทศและภาค'[เปลี่ยนจากปีก่อน (%)]), REMOVEFILTERS(), 'ดัชนีราคา ประเทศและภาค'[เดือน] = d, 'ดัชนีราคา ประเทศและภาค'[รหัสพื้นที่ (คีย์)] = "region:TG", 'ดัชนีราคา ประเทศและภาค'[รหัสหมวดสินค้า] = 0)
		formatString: 0.00
		lineageTag: 84d7bf93-f91b-4d11-a5ba-5c89df33af5b

	measure 'เงินเฟ้ออาหาร (%)' = VAR d = CALCULATE(MAX('ดัชนีราคา ประเทศและภาค'[เดือน]), REMOVEFILTERS()) RETURN CALCULATE(AVERAGE('ดัชนีราคา ประเทศและภาค'[เปลี่ยนจากปีก่อน (%)]), REMOVEFILTERS(), 'ดัชนีราคา ประเทศและภาค'[เดือน] = d, 'ดัชนีราคา ประเทศและภาค'[รหัสพื้นที่ (คีย์)] = "region:TG", 'ดัชนีราคา ประเทศและภาค'[รหัสหมวดสินค้า] = 10000)
		formatString: 0.00
		lineageTag: b9e887d3-f4af-4945-ac44-47ea982be835

	measure ข้อมูลถึงเดือน = FORMAT(CALCULATE(MAX('ดัชนีราคา ประเทศและภาค'[เดือน]), REMOVEFILTERS()), "mmm yyyy")
		lineageTag: d68dc2d7-c33b-4375-89a4-6580c9e638f5

	measure 'ดัชนีหมวดหลัก ทั้งประเทศ' = IF(SELECTEDVALUE('หมวดสินค้า'[รหัสหมวดสินค้า]) IN {0,10000,20000,30000,40000,50000,60000,70000}, CALCULATE(AVERAGE('ดัชนีราคา ประเทศและภาค'[ดัชนี (ปี 2566 = 100)]), 'ดัชนีราคา ประเทศและภาค'[รหัสพื้นที่ (คีย์)] = "region:TG"))
		formatString: 0.0
		lineageTag: f8b50731-94e6-40bc-8347-040e3149b9be

	column 'รหัสพื้นที่ (คีย์)'
		dataType: string
		lineageTag: 4bd32bcb-6723-4847-8c0c-68cc10ab2ff5
		summarizeBy: none
		sourceColumn: area_key

		annotation SummarizationSetBy = Automatic

	column รหัสหมวดสินค้า
		dataType: int64
		formatString: 0
		lineageTag: 981348fb-9eaf-430c-91ce-16c5ae1bbfaf
		summarizeBy: none
		sourceColumn: commodity_code

		annotation SummarizationSetBy = Automatic

	column เดือน
		dataType: dateTime
		formatString: Long Date
		lineageTag: 018871dc-2985-4400-9939-1e2616ab2623
		summarizeBy: none
		sourceColumn: period_date

		variation Variation
			isDefault
			relationship: 73114ddc-086f-48c5-a572-cc36875d4652
			defaultHierarchy: LocalDateTable_df996de3-3477-48e3-a8b9-2ec408110a3f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ดัชนี (ปี 2566 = 100)'
		dataType: double
		lineageTag: f25d9036-7551-46c9-91ce-295343646642
		summarizeBy: sum
		sourceColumn: index_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'เปลี่ยนจากเดือนก่อน (%)'
		dataType: double
		lineageTag: 2a83d472-1581-4eb9-9ab1-fcede26a13ae
		summarizeBy: sum
		sourceColumn: change_mom

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'เปลี่ยนจากปีก่อน (%)'
		dataType: double
		lineageTag: b5cfe4ca-333b-4df7-a88e-d247957dec2c
		summarizeBy: sum
		sourceColumn: change_yoy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'ดัชนีราคา ประเทศและภาค' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\cost-of-living-pipeline\exports\cost_of_living_powerbi_lite.xlsx"), null, true),
				    fact_cpi_region_monthly_Sheet = Source{[Item="fact_cpi_region_monthly",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(fact_cpi_region_monthly_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"area_key", type text}, {"commodity_code", Int64.Type}, {"period_date", type date}, {"index_value", type number}, {"change_mom", type number}, {"change_yoy", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

